# fly.toml app configuration file generated for rengobot on 2023-06-13T09:45:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rengobot"
primary_region = "ord"

[build]
  image = "katieoh/rengobot"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[mounts]
source="rengobot_data"
destination="/data"
